package entities

/*
id,
  name,
  description,
  price,
  whatsappMessage,
  image = "https://github.com/shadcn.png",
*/

//id not required, will be generated by DynamoDB

type Product struct {
	ID              string  `json:"product_id"`
	EstablishmentID string  `json:"establishment_id"`
	Name            string  `json:"name"`
	Description     string  `json:"description"`
	Price           float64 `json:"price"`
	// WhatsappMessage string  `json:"whatsappMessage"`
	// Image           string  `json:"image"`
	// IsActive        bool    `json:"isActive"`
	// OwnerID         string  `json:"ownerId"`
}
